### PR TITLE
Remove the marked_callsites function

### PR DESCRIPTION
**Pull request by livia01px2019**
## What Changed?

Removed the `marked_callsites` function and replaced it with `marked_sinks` and `filter` in the Lemmy property.

## Why Does It Need To?

Function is misleading and just uses `marked_sinks`.

## Checklist

- [x] Above description has been filled out so that upon quash merge we have a
  good record of what changed.
- [x] New functions, methods, types are documented. Old documentation is updated
  if necessary
- [x] Documentation in Notion has been updated
- [ ] Tests for new behaviors are provided
  - [ ] New test suites (if any) ave been added to the CI tests (in
    `.github/workflows/rust.yml`) either as compiler test or integration test.
    *Or* justification for their omission from CI has been provided in this PR
    description.

### CODE REVIEW

**Comment by JustusAdam** [comment]
Why are you merging this into `flows-to-primitive-updated`?

**Comment by livia01px2019** [comment]
> Why are you merging this into `flows-to-primitive-updated`?

It's branched off of that PR, so it contains all of those commits. Once I merge that one in this one should be good to go. It doesn't actually depend on it, I just thought that that one is close to merging to it shouldn't really matter.

**Comment by JustusAdam** [comment]
> It's branched off of that PR, so it contains all of those commits. Once I merge #80 in this one should be good to go. It doesn't actually depend on it, I just thought that #80 is close to merging so it shouldn't really matte

You know there's such a thing as git cherry-pick right? 😄

**Comment by livia01px2019** [comment]
> > It's branched off of that PR, so it contains all of those commits. Once I merge #80 in this one should be good to go. It doesn't actually depend on it, I just thought that #80 is close to merging so it shouldn't really matte
> 
> You know there's such a thing as git cherry-pick right? 😄

Too lazy :)

**Comment by JustusAdam** [comment]
> > > It's branched off of that PR, so it contains all of those commits. Once I merge #80 in this one should be good to go. It doesn't actually depend on it, I just thought that #80 is close to merging so it shouldn't really matte
> > 
> > 
> > You know there's such a thing as git cherry-pick right? 😄
> 
> Too lazy :)

Maybe, but if you had done that this one cold have been merged already. Also now you need to re-point it at `main`

**Comment by JustusAdam** [comment]
Like I can't review the PR because it doesn't actually show the changes with `main`

**Comment by livia01px2019** [comment]
> Like I can't review the PR because it doesn't actually show the changes with `main`. Though in this case that's not a problem, because the changes are quite straight forward 😄

Hopefully it's in an ok state now? I've fixed all the merge conflicts with main.

**Pull request merged**
